#!/bin/bash
set -e #Fail on any error

cores=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || sysctl -n hw.ncpu || echo "$NUMBER_OF_PROCESSORS")
echo "About to use $cores cores";

#build
# cmake --build build --target install; 


if [ "$1" = "" ]; then
    proj="template"
else
    proj=$1
fi

if [ "$2" != "" ]; then
    cores=$2
fi

cmake --build build --target ${proj}-re; #-v for verbose
cd examples/$proj

# module load intelMPI
# [ $(uname) = "Linux" ] && source /opt/intel/Compiler/19.0/bin/compilervars.sh arch intel64
shift; 
shift;
echo ":::Remaining params passed to app [$@]"
[ $(uname) = "Linux" ] && mpirun -np $cores ./qsf-${proj}-re $@
# [ $(uname) = "Linux" ] && mpirun -np 2 valgrind --leak-check=yes --show-leak-kinds=all --verbose ./${what}

[ $(uname) = "Darwin" ] && mpirun --host localhost:$cores ./qsf-${proj}-re $@