#!/bin/bash
set -e #Fail on any error

cores=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || sysctl -n hw.ncpu || echo "$NUMBER_OF_PROCESSORS")

if [ -n "$1" ]; then
    proj=$1
    shift; 
else
    proj="template"
fi

if [ -n "$1" ]; then
    cores=$1
    shift;
fi

echo "About to use $cores cores";

cmake --build build --target ${proj}-im; #-v for verbose
cd examples/$proj

# module load intelMPI
# [ $(uname) = "Linux" ] && source /opt/intel/Compiler/19.0/bin/compilervars.sh arch intel64


echo "\n:::Remaining params passed to app [$@]"
[ $(uname) = "Linux" ] && mpirun -np $cores ./qsf-${proj}-im $@
# [ $(uname) = "Linux" ] && mpirun -np 2 valgrind --leak-check=yes --show-leak-kinds=all --verbose ./${what}

[ $(uname) = "Darwin" ] && mpirun --host localhost:$cores ./qsf-${proj}-im $@



# [ $(uname) = "Darwin" ] && mpirun --mca btl vader,self,tcp -np 8 ./${what} $3
# [ $(uname) = "Darwin" ] && [ $(uname -m) = "arm64" ] && mpirun -np 2 ./${what} $3
# [ $(uname) = "Darwin" ] && [ $(uname -m) = "x86_64" ] && mpirun -np 4 ./${what} $3


# skipplots=false
# autoopen=true
# autoopenmerged=false

# [ "$skipplots" = true ] && exit 0

# REL="../../../"
# cd Results

# shopt -s nullglob
#1D
# FILES=mom*x.dat
# for f in $FILES
# do
#   echo "Processing $f file..."
#   gnuplot -e "filename='$f'" -e "xaxis=\"p [au]\"" "${REL}plots/wf1d.gnu"
#   [ "$autoopen" = true ] && open "${f%.*}.pdf"
# done
# FILES=psi*x.dat
# for f in $FILES
# do
#   echo "Processing $f file..."
#   gnuplot -e "filename='$f'" -e "xaxis=\"x [au]\"" "${REL}plots/wf1d.gnu"
#   [ "$autoopen" = true ] && open "${f%.*}.pdf"
# done

# # 2D
# FILES=mom*xy.dat
# for f in $FILES
# do
#   echo "Processing $f file..."
#   gnuplot -e "filename='$f'" -e "xaxis=\"p_x [au]\"" -e "yaxis=\"p_y [au]\"" "${REL}plots/wf2d.gnu"
#   [ "$autoopen" = true ] && open "${f%.*}.pdf"
# done

# FILES=$(ls psi*xy.dat | sort -n -t _ -k 2) 
# # FILES=psi*xy.dat
# for f in $FILES
# do
#   echo "Processing $f file..."
#   gnuplot -e "filename='$f'" -e "xaxis=\"x [au]\""  -e "yaxis=\"y [au]\"" "${REL}plots/wf2d.gnu"
#   [ "$autoopen" = true ] && open "${f%.*}.pdf"
# done
# #JOIN
# gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -dPDFSETTINGS=/prepress -sOutputFile=psi_xy_merged.pdf psi*xy.pdf
# [ "$autoopenmerged" = true ] && open psi_xy_merged.pdf
#HHG'S
# FILES=hhg*.dat
# for f in $FILES
# do
#   echo "Processing $f file..."
#   gnuplot -e "filename='$f'" "${REL}plots/hhg.gnu"
#   [ "$autoopen" = true ] && open "${f%.*}.pdf"
# done

# Fields
# FILES=exf*.dat
# for f in $FILES
# do
#   echo "Processing $f file..."
#   gnuplot -e "filename='$f'" "${REL}plots/exf.gnu"
#   [ "$autoopen" = true ] && open "${f%.*}.pdf"
# done